#!/bin/bash

sudo apt-get update
sudo apt-get upgrade

echo "Seting Up bridged network connection"
#Determine which network interface to use
ETHER=$(ip addr | grep 2: | grep -o "e.*:" | cut -d ":" -f 1 -)

#Install bridge utils
sudo  apt-get install bridge-utils -y

#modify network interfaces
sudo chmod 777 /etc/network/interfaces

echo "" >> /etc/network/interfaces
echo "auto $ETHER" >> /etc/network/interfaces
echo "iface $ETHER inet manual" >> /etc/network/interfaces
echo "" >> /etc/network/interfaces

echo "auto xenbr0" >> /etc/network/interfaces
echo "iface xenbr0 inet dhcp" >> /etc/network/interfaces
echo "bridge_ports $ETHER" >> /etc/network/interfaces
echo "" >> /etc/network/interfaces

sudo chmod 644 /etc/network/interfaces

#restert network interfaces
sudo systemctl restart networking

#install dependicies for rest of install
echo "Installing dependicies:"
sudo apt-get install git bin86 bcc python-dev iasl uuid-dev libcurses-ocaml-dev libperl-dev libgtk2.0-dev libaio-dev libyajl-dev bison git libc6-dev-i386 texinfo libsdl2-dev libssl-dev mesa-common-dev libepoxy-dev libdrm-dev libgbm-dev xbfdt-dev en-utils-common -y

echo "Copying Files, This could take a while, >10min if using HDD"

#set up files
sudo cp -rf xen-disks /xen-disks
sudo cp -rf gfedora.cfg /gfedora.cfg

cd /
mkdir xen-disks
cd xen-disks
wget https://download.fedoraproject.org/pub/fedora/linux/releases/24/Workstation/x86_64/iso/Fedora-Workstation-netinst-x86_64-24-1.2.iso
dd if=/dev/zero of=fedora(24)-disk-1.img bs=1M count=10000


#install xen
echo""
echo "Installing xen from git"
echo""

cd ~/

git clone git://xenbits.xen.org/xen.git

cd ~/xen/
./configure 
make 
sudo make install 

#modify fstab
sudo chmod 777 /etc/fstab
echo "none /proc/xen xenfs defaults 00" >> /etc/fstab
sudo chmod 644 /etc/fstab

#install virGL - could use some fine tuning
echo""
echo "Installing most recent virglrenderer from git"
echo""
sudo apt-get install autotools-dev autoconf libtool -y
cd ~/
git clone git://people.freedesktop.org/~airlied/virglrenderer
cd ~/virglrenderer/
aclocal 
libtoolize
aclocal 
autoconf 
automake --add-missing 
libtoolize
autoreconf
automake
./configure
make
sudo make install 

#install qemu
echo""
echo "Installing most recent qemu from git"
echo""
cd ~/
git clone git://git.qemu.org/qemu.git
cd ~/qemu/

./configure --enable-gtk --enable-sdl --with-sdlabi=2.0 --enable-opengl --enable-virglrenderer
make
sudo make install

#update grub
sudo update-grub
#move cfg file to xen folder
sudo cp -rf /gfedora.cfg /etc/xen/gfedora.cfg
#check for updates
sudo apt-get update -y
sudo apt-get upgrade -y
#install xenutils
sudo apt-get install xen-utils-4.6 -y

#setup script to run on boot to start xencommons
echo "#!/bin/bash" > startXen
echo "sudo etc/init.d/xencommons start" >> startXen
sudo chmod ugo+x startXen
sudo mv startXen /etc/init.d/startXen
sudo update-rc.d startXen defaults

